# Generated by Django 5.2.11 on 2026-02-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_domain', models.CharField(max_length=100)),
                ('company_website', models.URLField()),
                ('point_of_contact', models.CharField(max_length=100)),
                ('reply', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('planning_to_offer', models.TextField(blank=True, null=True)),
                ('availability_for_meeting', models.TextField(blank=True, null=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('proposed', models.TextField(blank=True, null=True)),
                ('meeting_1', models.TextField(blank=True, null=True)),
                ('meeting_2', models.TextField(blank=True, null=True)),
                ('quotation', models.TextField(blank=True, null=True)),
                ('follow_ups', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
        ),
    ]
