# Generated by Django 5.2.11 on 2026-02-19 10:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_dashboard_sheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='dashboard_sheet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dashboard_sheet',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='availability_for_meeting',
            field=models.TextField(blank=True, db_column='meetingAvailability', null=True),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='company_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='company_name',
            field=models.CharField(db_column='CompanyName', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='meeting_1',
            field=models.TextField(blank=True, db_column='meet_1', null=True),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='meeting_2',
            field=models.TextField(blank=True, db_column='meet_2', null=True),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='meeting_date',
            field=models.DateTimeField(blank=True, db_column='meetingDate', null=True),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='point_of_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='quotation',
            field=models.TextField(blank=True, db_column='quotes', null=True),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='status',
            field=models.CharField(blank=True, choices=[('Under Progress', 'Under Progress'), ('Interested', 'Interested'), ('Awaiting for Meeting', 'Awaiting for Meeting'), ('Quotation', 'Quotation'), ('Skip', 'Skip')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='dashboard_sheet',
            table='core_dashboard_sheet',
        ),
    ]
