# Generated by Django 5.2.11 on 2026-02-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='company_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='company_name',
            field=models.CharField(db_column='CompanyName', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
