# Generated by Django 5.2.11 on 2026-02-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dashboard_sheet_company_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='company_website',
            field=models.URLField(max_length=255),
        ),
    ]
