# Generated by Django 5.2.11 on 2026-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dashboard_sheet_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='point_of_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
