# Generated by Django 5.2.11 on 2026-02-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dashboard_sheet_point_of_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='company_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
