# Generated by Django 5.2.11 on 2026-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dashboard_sheet_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='meeting_date',
            field=models.DateField(blank=True, db_column='meetingDate', null=True),
        ),
    ]
