# Generated by Django 5.2.11 on 2026-02-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dashboard_sheet_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='meeting_date',
            field=models.DateTimeField(blank=True, db_column='meetingDate', null=True),
        ),
    ]
