# Generated by Django 5.2.11 on 2026-02-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dashboard_sheet_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_sheet',
            name='meeting_discussion',
            field=models.TextField(blank=True, db_column='meet_discuss', null=True),
        ),
    ]
