# Generated by Django 5.2.11 on 2026-02-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dashboard_sheet_meeting_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard_sheet',
            name='proposed',
        ),
    ]
