# Generated by Django 5.2.11 on 2026-03-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_dashboard_sheet_proposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_sheet',
            name='Next_follow_up_date',
            field=models.DateTimeField(blank=True, db_column='next_follow_up_date', null=True),
        ),
        migrations.AddField(
            model_name='dashboard_sheet',
            name='last_follow_up_date',
            field=models.DateTimeField(blank=True, db_column='last_follow_up_date', null=True),
        ),
    ]
