# Generated by Django 5.2.11 on 2026-03-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dashboard_sheet_next_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='last_follow_up_date',
            field=models.DateTimeField(blank=True, db_column='Last Follow up date', null=True),
        ),
    ]
