# Generated by Django 5.2.11 on 2026-03-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_dashboard_sheet_last_follow_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_sheet',
            name='status',
            field=models.CharField(blank=True, choices=[('Under Progress', 'Under Progress'), ('Interested', 'Interested'), ('Awaiting for Meeting', 'Awaiting for Meeting'), ('Quotation', 'Quotation'), ('Skip', 'Skip'), ('Not Interested', 'Not Interested')], max_length=100, null=True),
        ),
    ]
