# Generated by Django 5.2.11 on 2026-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_dashboard_sheet_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard_sheet",
            name="Next_follow_up_date",
        ),
        migrations.RemoveField(
            model_name="dashboard_sheet",
            name="last_follow_up_date",
        ),
        migrations.AddField(
            model_name="dashboard_sheet",
            name="follow_up_1",
            field=models.DateTimeField(blank=True, db_column="follow_up_1", null=True),
        ),
        migrations.AddField(
            model_name="dashboard_sheet",
            name="follow_up_2",
            field=models.DateTimeField(blank=True, db_column="follow_up_2", null=True),
        ),
        migrations.AddField(
            model_name="dashboard_sheet",
            name="follow_up_3",
            field=models.DateTimeField(blank=True, db_column="follow_up_3", null=True),
        ),
    ]
